# Generated by Django 4.2.9 on 2024-01-31 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='district')),
                ('wikipedia_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('description', models.TextField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('timing', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='branch')),
                ('service', models.TextField(blank=True)),
                ('faq', models.TextField(blank=True)),
                ('testimonials', models.TextField(blank=True)),
                ('loan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_loan', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ('name',),
            },
        ),
    ]
